// <auto-generated />
using CardapioDigitalWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardapioDigitalWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220117023256_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("CardapioDigitalWebAPI.Models.Bebidas", b =>
                {
                    b.Property<int>("BEB_ID1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BEB_DESC1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BEB_NOME1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BEB_TIPO1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BEB_UM1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BEB_VALOR1")
                        .HasColumnType("TEXT");

                    b.HasKey("BEB_ID1");

                    b.ToTable("Bebidas");
                });

            modelBuilder.Entity("CardapioDigitalWebAPI.Models.Pizzas", b =>
                {
                    b.Property<int>("PIZ_ID1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PIZ_DESC1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PIZ_GRANDE1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PIZ_MEDIA1")
                        .HasColumnType("TEXT");

                    b.Property<string>("PIZ_NOME1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PIZ_TREM1")
                        .HasColumnType("TEXT");

                    b.HasKey("PIZ_ID1");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("CardapioDigitalWebAPI.Models.Usuarios", b =>
                {
                    b.Property<int>("USR_ID1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("USR_LOCKED1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("USR_LOGIN1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("USR_NAME1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("USR_PASSWORD1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("USR_ID1");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            USR_ID1 = 1,
                            USR_LOCKED1 = 0,
                            USR_LOGIN1 = "admin",
                            USR_NAME1 = "Administrador",
                            USR_PASSWORD1 = "75b82c0c9eb6c6c1beb454d04117e55f"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
